version: '3'
services:
  postgresql:
    container_name: postgresql-drivers
    image: postgres:11.2-alpine
    command: postgres -c 'max_connections=500'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: drivers
    restart: always
    shm_size: '256mb'
    ports:
      - 5432:5432
